### ISSUE TITLE
GPS Processing

### ISSUE THREAD

**Issue by tpreynolds** [uw-adcs-krish/uw_cubesat_adcs#16]
Secondary software test for this library.

**Comment by uw-adcs-krish** [comment]
- Put rate transitions inside GPS_processing_lib, instead of outside
- Why is gps_time being passed regardless of validity?
- We should have a time simulation library that chooses between GPS, or spacecraft propagated time, because ADCS isn't handling time updates / propagation
- We need to talk about how FSW is assuming time is coming in - it looks like currently FSW thinks it's getting time solely from the GPS which is not always true

**Comment by tpreynolds** [comment]
- Added rate transitions
- updated so that when GPS is not valid, MET gets used.
- Added library to create MET using J2000_TT epoch. Also added library to convert this to GPS time.
