### ISSUE TITLE
**Disturbances**

### ISSUE THREAD

**Issue by tpreynolds** [uw-adcs-krish/uw_cubesat_adcs#23]
Secondary software test for this library.

**Comment by MathiasKerman** [comment]
Test file updates due to obsolete libraries used:

environment_test.slx:
- changed signal names in environment_test.slx to match the new bus signal names
- max torques for dipole, gravity, solar pressure and drag look reasonable

disturbances_test.slx:
- updated time_coord_rotation_lib block in the subsystem takin in the GPS_time_lib at the top
- tle2eci_coarse_lib needed a second teme_2_eci input
- disturbance torques all look like they are the right orders of magnitude
- >1,000,000m altitude error after ~1750s

aero_drag_test.slx
- updated logsout variable name
- torque about 10^(-9) Nm

grav_dist_test.slx
- Acceleration due to gravity is: 8.4464m/s2 at 500km altitude and 47.1299 deg latitude

mag_vec_test.slx
- Test 1: Difference in computed field strength is: 10.2372nT

**Comment by tpreynolds** [comment]
Is there still an error after 1750s? This should stay open if so.
