### ISSUE TITLE
**TLE to ECI Conversion**

### ISSUE THREAD

**Issue by tpreynolds** [uw-adcs-krish/uw_cubesat_adcs#32]
Seconday software test of this library. Used in FSW - sensor processing.

**Comment by uw-adcs-krish** [comment]
- Comment for standard gravitational parameter should have units km^3 / s^2
- Convert mean motion to radps when it's declared (like the others)
- I don't like while-loops -- if they are unbounded it can cause the software to hang
  - Change the while loop to a for-loop and leave the convergence tolerance check as a if-break condition inside
  - We should only use for-loops in embedded matlab functions, since it is clearer code
  - Matlab coder will autocode a bounded while-loop as a for-loop in C++ anyways
- Why use this Danby's method for solving Kepler's equations when a simple newton-method works fine?
  - Have you verified this against another kepler solver?
  - This method includes support for hyperbolic trajectories, which we should never have
    - Instead, remove this code and put validity checks on the orbit
- Remove commented code if it's not being used
- Rename kepler1() to kepler - it is the only keplerian solver being used
- Why duplicate the teme_2_eci input instead of splitting a single input?
- Why is tle2eci_coarse_lib.slx in matlab/tools? It should be its own library in adcs_sim/lib/ and the name should be tle2eci_lib.slx
- Verified that eci2tle_lib and tle2eci_lib are consistent with each other to within sub-millimeter accuracy

**Comment by tpreynolds** [comment]
Have made all of these changes. Noticed a bug in the mean motion calculation in RV2OEV , will revisit this. Will also test the new kepler solver against Vallado example.

**Comment by tpreynolds** [comment]
Fixed all bugs + added tests of RV2OEV, OEV2RV and kepler functions. Also updated libraries with hooks for various divide by zero conditions and non-elliptic orbit stuff.
