### ISSUE TITLE
Quaternion Wobble

### ISSUE THREAD

**Issue by tpreynolds** [uw-adcs-krish/uw_cubesat_adcs#89]
The SIMs quaternion seems to "wobble" about the EKFs estimated quaternion when executing a pointing maneuver. The fig attached shows what I mean. 

Possible reasons? 
- constant rw desat is inducing some kind of oscillation in the true quaternion.
- converting to fixed step integration wasn't done all that properly and something got messed up

Stuff is located in the **tay-fixed-step** branch.

![quat_true_v_ekf](https://user-images.githubusercontent.com/29679775/43866187-da733f42-9b32-11e8-83e2-fa2f8d0106e3.png)

**Comment by uw-adcs-krish** [comment]
I briefly remember bringing up a similar issue a long time ago where I noticed the estimated bias was oscillating with a similar period to what we're seeing above. I think the estimated attitude may not be wobbling because the error is getting soaked up into the bias estimation. Can you plot the EKF bias estimate?

**Comment by MathiasKerman** [comment]
I remember this as well, but I was not able to reproduce it at the time. Wasn't your wobble also a much higher amplitude?

**Comment by tpreynolds** [comment]
Here's the bias and two quaternion trajectories: 

![quat_true_v_ekf](https://user-images.githubusercontent.com/29679775/43967048-7d48adf6-9c91-11e8-92ad-34058d87f456.png)

**Comment by uw-adcs-krish** [comment]
I'd be curious to see a longer timeline with multiple periods to see if the bias is in fact soaking up the error; it looks like the y-axis estimated bias is. If that's the case, this would suggest an issue with how we're using the mag-field vector as an inertial measurement in the KF (I think). If the mag-field is bouncing around, then we should see oscillations around the Sun vector, since we prioritize the sun vector measurement. Are we sun pointing in this attitude with the y-axis? I wonder if the amplitude of oscillation is correlated to the measurement noise weighting on the mag sensor in the KF - try playing with this value.

**Comment by tpreynolds** [comment]
Hard yes on the bias soaking up the error. We remain sun pointing in this case, sun sensor angles are oscillating roughly +/- 10 degrees around the desired angles. I'll try playing with the meas noise weightings and see what happens

![ekf_bias](https://user-images.githubusercontent.com/29679775/43975520-f95f881e-9cab-11e8-90b4-3e28c1b0f4c8.png)

**Comment by tpreynolds** [comment]
A little elbow grease later. Pic is EKF state and true quaternion over one orbit. The wobble was fixed by updating some parameters in the gyro model, as well as noise values sun sensor model. Some equations in EKF were updated as well.

![quat_fix](https://user-images.githubusercontent.com/29679775/44496290-b3307480-a628-11e8-91c4-8397c0bee31d.png)

**Comment by uw-adcs-krish** [comment]
Nice. Could you add some details on what parameters and equations got changed?

**Comment by tpreynolds** [comment]
Tried to in the pull req. The main thing is that the \Delta t parameter in the propagation equations can't be the gyro update rate, which is what it's supposed to be according to Crassidis. It's meant to be the rate at which the incoming omega value is updated, so in our case that's the library sample time. 

Equations I changed were the DCM to convert inertial to body in the update step, and then just cosmetic updates to the propagation equations. We were calculating a matrix using scalar last (Crassidis convention) and then transforming -- replaced this with just the original matrix in scalar first form.

I also changed the ARW/RRW parameters based on Crassidis example 7.1. Ours were made up (and really high) before. Unrelated to the wobble error, but each axis noise seed was the same, so I changed that too. This made it obvious that the body rates were being tracked well all along, and pointed me to the error coming from the quaternion propagation step (how I found the \Delta t thing)
